import { BillingPlan, MeetingConfiguration, UserPreferences } from '@mivo/types';

export const APP_CONFIG = {
  name: 'Mivo Collab',
  tagline: 'Connect • Collaborate • Communicate',
  company: 'HyperDevelopers',
  version: '1.0.0',
  defaultPort: {
    web: 3000,
    api: 4000,
    signaling: 4001,
    worker: 4002,
  },
  urls: {
    web: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
    api: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000',
    signaling: process.env.NEXT_PUBLIC_SIGNALING_URL || 'http://localhost:4001',
  },
  meetingIdPrefix: 'mivo',
  tokenExpiry: '7d',
};

export const DEFAULT_USER_PREFERENCES: UserPreferences = {
  theme: 'dark',
  defaultMicMuted: false,
  defaultCamMuted: false,
  noiseSuppression: true,
  echoCancellation: true,
  hdVideo: true,
  emailNotifications: true,
  soundAlerts: true,
};

export const DEFAULT_MEETING_CONFIG: MeetingConfiguration = {
  waitingRoom: false,
  allowScreenShare: true,
  allowChat: true,
  muteOnEntry: false,
  videoOnEntry: true,
  requireAuth: false,
  recordingEnabled: false,
  aiTranscription: true,
};

export const BILLING_PLANS: BillingPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    tagline: 'Ideal for individual discovery and quick 1-on-1 calls.',
    priceMonthly: 0,
    priceYearly: 0,
    maxParticipants: 50,
    maxMeetingDurationMinutes: 45,
    cloudRecordingHours: 0,
    aiTranscription: false,
    customBranding: false,
    ssoEnabled: false,
    slaSupport: false,
    features: [
      'Up to 50 participants',
      '45-minute group meeting limit',
      'Unlimited 1-on-1 instant meetings',
      'Interactive screen sharing & meeting chat',
      'HD Audio & Video (WebRTC)',
      'Basic dashboard & meeting history',
    ],
  },
  {
    id: 'pro',
    name: 'Pro Professional',
    tagline: 'For fast-moving professionals and power creators.',
    priceMonthly: 12,
    priceYearly: 120,
    maxParticipants: 150,
    maxMeetingDurationMinutes: 1440,
    cloudRecordingHours: 10,
    aiTranscription: true,
    customBranding: false,
    ssoEnabled: false,
    slaSupport: false,
    features: [
      'Up to 150 participants',
      'Unlimited meeting duration (24h)',
      '10 Hours Cloud Recording storage',
      'AI Meeting Summaries & Action Items',
      'Automated speech-to-text transcription',
      'Priority RTC signaling & TURN relay',
      'Meeting scheduler with calendar export',
    ],
  },
  {
    id: 'business',
    name: 'Business Team',
    tagline: 'Designed for teams, organizations, and growing businesses.',
    priceMonthly: 28,
    priceYearly: 280,
    maxParticipants: 500,
    maxMeetingDurationMinutes: 1440,
    cloudRecordingHours: 100,
    aiTranscription: true,
    customBranding: true,
    ssoEnabled: true,
    slaSupport: true,
    features: [
      'Up to 500 participants',
      'Multi-team workspace & member roles',
      '100 Hours Cloud Recording with search',
      'Advanced AI meeting knowledge search',
      'Custom company branding & custom links',
      'SSO / SAML authentication integration',
      'Detailed audit logs & usage telemetry',
      '99.9% Uptime SLA & 24/7 dedicated support',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise Ultra',
    tagline: 'Custom compliance, dedicated media clusters, and enterprise SLA.',
    priceMonthly: 79,
    priceYearly: 790,
    maxParticipants: 1000,
    maxMeetingDurationMinutes: 1440,
    cloudRecordingHours: 1000,
    aiTranscription: true,
    customBranding: true,
    ssoEnabled: true,
    slaSupport: true,
    features: [
      'Up to 1,000+ interactive participants',
      'Dedicated private SFU & media routing cluster',
      'SCIM user provisioning & Directory sync',
      'Custom data retention & compliance policies',
      'On-premise / hybrid deployment options',
      'Dedicated Customer Success Manager',
      'Custom AI models & localized transcription',
    ],
  },
];

export const ICE_SERVERS_CONFIG: RTCConfiguration = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
    { urls: 'stun:stun2.l.google.com:19302' },
  ],
  iceCandidatePoolSize: 10,
};
