FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/signaling/ ./apps/signaling/

RUN npm install
RUN npm run build --workspaces --if-present

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps/signaling ./apps/signaling
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 4001
CMD ["npm", "run", "start", "--workspace=@mivo/signaling"]
